// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function GetBranches():Promise<Array<main.Branch>>;

export function GetWeekReport(arg1:string,arg2:string):Promise<models.Report>;
