// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GenerateAndSend(arg1:string, arg2:string):Promise<void>;

export function LoadConfig():Promise<models.Config>;

export function SaveConfig(arg1:models.Config):Promise<void>;
