// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetWeekReport(arg1, arg2) {
  return window['go']['main']['App']['GetWeekReport'](arg1, arg2);
}
